services:

  eureka:
    image: eclipse-temurin:21-jre
    volumes:
      - ./local-jars/insighton-eureka.jar:/app/app.jar:ro
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD_TEST:-devpassword}
