spring.application.name=insighton-gateway
server.port=8080

jwt.public-key-base64=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFtbG1Iem92eTBGbE9VSVE1a0JUUgorNjdlS1RVbWUvYzZIYmI0aU1rV09mbEJIa2tOemFZY2NJZHFKT3QzS091MnJnMVlWU25EUzRqWStvMXJkMGNuCkpRbnNSeUwyamZHSmFQNUVlemdxdVJMSFZ3Rm1UT1NSWVlxQndVemR2T1NxS2VSMzJMNHpJL0prYVFpVVpxVDYKNHphTk9vSGJLcTBkcEwyMVNsVUd3SWhaYU1WQlM5Um8zQThpSis5bXFMSWwraDZJc29FTnNJU2psdDU5Tmx4aAo4bExibjZmVUVQL0c3SnhEMUdHMVBoQTNTTVRRbG9KajB3ZkR3MmFaRFAwcE5BQXlDWHgzZzFGYUxMenlveU5vCjkyMVY3SEdhS3ZKOVk4R3ptUklXcmZ2NG5zMXYxTlowYzQzOU1LK2lMMzR5WUpMYjZSKzhoMEJaSnF6L1dRNVgKYlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

gateway-route.auth=http://insighton-auth
gateway-route.ai=http://insighton-ai
gateway-route.rule=http://insighton-ruleengine
gateway-route.core=http://insighton-core

server.shutdown=graceful