spring.application.name=insighton-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://insighton-eureka:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health
