spring.application.name=insighton-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://insighton-eureka:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health

spring.cloud.gateway.server.webmvc.routes[0].id=insighton-front
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://insighton-front
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/front/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=insighton-auth
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://insighton-auth
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=insighton-core
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://insighton-core
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/core/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[3].uri=lb://insighton-ai
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/ai/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[4].id=insighton-ruleengine
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://insighton-ruleengine
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/rule-engine/**
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=StripPrefix=1