spring.application.name=insighton-gateway
server.port=8080

spring.config.import=classpath:config/dev/actuator.properties, classpath:config/dev/zipkin.properties

gateway-route.auth=http://localhost:8000
gateway-route.ai=http://localhost:8100
gateway-route.rule=http://localhost:8200
gateway-route.core=http://localhost:8300

logging.level.root=INFO
logging.level.com.nhnacademy.insightongateway=DEBUG