management.endpoints.web.exposure.include=health, info, prometheus, gateway
management.tracing.export.zipkin.endpoint=http://insighton-zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.readinessState.enabled=true

