springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs
springdoc.swagger-ui.urls[1].name=Core Service
springdoc.swagger-ui.urls[1].url=/core/v3/api-docs
springdoc.swagger-ui.urls[2].name=AI Service
springdoc.swagger-ui.urls[2].url=/ai/v3/api-docs
springdoc.swagger-ui.urls[3].name=Rule Engine Service
springdoc.swagger-ui.urls[3].url=/ruleengine/v3/api-docs
springdoc.swagger-ui.path=/api/swagger